task:
  matrix:
    - name: CI - Go@1.12
      container:
        image: golang:1.12-buster
    - name: CI - Go@1.13
      container:
        image: golang:1.13
  env:
    GOPROXY: https://proxy.golang.org
  populate_dependencies_script: |
    cd src
    go get -v -t -d ./...
  build_script: |
    cd src
    go build -o gosh *.go
    touch ${GOPATH}/bin/history.txt
    mv gosh ${GOPATH}/bin

docker_builder:
  name: Docker Build
  build_script: |
    docker build --tag gosh:latest .
    docker pull docker.pkg.github.com/gosh-terminal/gosh/gosh
    docker run -it gosh
