task:
  matrix:
    - name: CI - Go@1.12
      container:
        image: golang:1.12-buster
    - name: CI - Go@1.13
      container:
        image: golang:1.13
  env:
    GOPROXY: https://proxy.golang.org
  populate_dependencies_script: |
    go get -v -t -d ./...
  build_script: |
    go build -o gosh *.go
    touch ${GOPATH}/bin/history.txt
    mv gosh ${GOPATH}/bin
  test_bootstrap_script: wget https://api.cirrus-ci.com/v1/artifact/task/6359555328180224/distrib/dist/goshSuite
  test_script: |
    chmod +x ./goshSuite
    ./goshSuite

docker_builder:
  name: Docker Build
  build_script: |
    docker build --tag gosh:latest .
