task:
  matrix:
    - name: CI - Go@1.12
      container:
        image: golang:1.12-buster
    - name: CI - Go@1.13
      container:
        image: golang:1.13
  env:
    GOPROXY: https://proxy.golang.org
  go_modules_cache:
    folder: $GOPATH/pkg/mod
    populate_script: |
      cd src
      go get -v -t -d ./...
  build_script: |
    cd src
    go build -o gosh *.go
    touch ${GOPATH}/bin/history.txt
    mv gosh ${GOPATH}/bin

task:
  name: Test Docker Image
  container:
    image: docker
  env:
    CIRRUS_SHELL: direct
    CIRRUS_WORKING_DIR: /workspace
  build_script: docker build -f Dockerfile .
