image:
  file: .gitpod.Dockerfile

tasks:
  #  - init:  mkdir ../go ../go/bin && dh_auto_install
   - command: ./tools/setup2.0.bash && gosh

ports:
  - port: 8080
    onOpen: ignore
  - port: 4000
    onOpen: open-preview

vscode:
  extensions:
    - DavidAnson.vscode-markdownlint@0.32.0:gujQ1foJzJ2yxCOgDqFfXw==
    - mdickin.markdown-shortcuts@0.12.0:h8L11R6NpkgnCtbr8QLlUw==
    - timonwong.shellcheck@0.8.1:16BMw7Jrwd/KkAhJrkHwqQ==
