image:
  file: .gitpod.Dockerfile
tasks:
  - init: go install
    command: gosh
vscode:
  extensions:
    - DavidAnson.vscode-markdownlint@0.32.0:gujQ1foJzJ2yxCOgDqFfXw==
    - mdickin.markdown-shortcuts@0.12.0:h8L11R6NpkgnCtbr8QLlUw==
    - timonwong.shellcheck@0.8.1:16BMw7Jrwd/KkAhJrkHwqQ==
    - premparihar.gotestexplorer@0.1.10:jvUM8akrQ67vQxfjaxCgCg==
github:
  prebuilds:
    addBadge: true
    branches: true
    pullRequestsFromForks: true
    addLabel: prebuilt
