#!/bin/bash
randNum=$((1 + RANDOM % 19))
if [ $randNum -eq 1 ]; then
	echo -e "\e[1m\e[92m
          GGGGGGGGGGGGG                                 hhhhhhh
      GGG::::::::::::G                                 h:::::h
    GG:::::::::::::::G                                 h:::::h
    G:::::GGGGGGGG::::G                                 h:::::h
  G:::::G       GGGGGG   ooooooooooo       ssssssssss   h::::h hhhhh
  G:::::G               oo:::::::::::oo   ss::::::::::s  h::::hh:::::hhh
  G:::::G              o:::::::::::::::oss:::::::::::::s h::::::::::::::hh
  G:::::G    GGGGGGGGGGo:::::ooooo:::::os::::::ssss:::::sh:::::::hhh::::::h
  G:::::G    G::::::::Go::::o     o::::o s:::::s  ssssss h::::::h   h::::::h
  G:::::G    GGGGG::::Go::::o     o::::o   s::::::s      h:::::h     h:::::h
  G:::::G        G::::Go::::o     o::::o      s::::::s   h:::::h     h:::::h
  G:::::G       G::::Go::::o     o::::ossssss   s:::::s h:::::h     h:::::h
    G:::::GGGGGGGG::::Go:::::ooooo:::::os:::::ssss::::::sh:::::h     h:::::h
    GG:::::::::::::::Go:::::::::::::::os::::::::::::::s h:::::h     h:::::h
      GGG::::::GGG:::G oo:::::::::::oo  s:::::::::::ss  h:::::h     h:::::h
          GGGGGG   GGGG   ooooooooooo     sssssssssss    hhhhhhh     hhhhhhh
  \e[39m"
elif [ $randNum -eq 2 ]; then
	echo -e "\e[1m\e[92m
  ____           _
 / ___| ___  ___| |__
| |  _ / _ \/ __| '_ \\
| |_| | (_) \__ \ | | |
 \____|\___/|___/_| |_|
 \e[39m"
elif [ $randNum -eq 3 ]; then
	echo -e "\e[1m\e[92m
       ______           __
      / ____/___  _____/ /_
     / / __/ __ \\/ ___/ __ \\
    / /_/ / /_/ (__  ) / / /
    \\____/\\____/____/_/ /_/
    \e[39m"
elif [ $randNum -eq 4 ]; then
	echo -e "\e[1m\e[92m
    //   ) )
   //         ___      ___     / __
  //  ____  //   ) ) ((   ) ) //   ) )
 //    / / //   / /   \ \    //   / /
((____/ / ((___/ / //   ) ) //   / /
    \e[39m"
elif [ $randNum -eq 5 ]; then
	echo -e "\e[1m\e[92m
       >===>
     >>    >=>                     >=>
    >=>            >=>      >===>  >=>
    >=>          >=>  >=>  >=>     >=>>=>
    >=>   >===> >=>    >=>   >==>  >=>  >=>
     >=>    >>   >=>  >=>      >=> >>   >=>
      >====>       >=>     >=> >=> >=>  >=>

    \e[39m"
elif [ $randNum -eq 6 ]; then
	echo -e '\e[1m\e[92m
   /\\\\
 /\    /\\                        /\\
/\\             /\\       /\\\\   /\\
/\\           /\\  /\\   /\\      /\ /\
/\\   /\\\\  /\\    /\\    /\\\   /\\  /\\
 /\\    /\    /\\  /\\       /\\  /\   /\\
   /\\\\\        /\\      /\\ /\\  /\\  /\\
\e[39m'
elif [ $randNum -eq 7 ]; then
	echo -e '\e[1m\e[92m
 _____                 _
|  __ \               | |
| |  \/   ___    ___  | |__
| | __   / _ \  / __| | _ \\\
| |_\ \ | (_) | \__ \ | | | |
 \____/  \___/  |___/ |_| |_|
\e[39m'
elif [ $randNum -eq 8 ]; then
	echo -e '\e[1m\e[92m
 _ (_)(_)(_) _                                (_)
(_)         (_)    _  _  _       _  _  _  _   (_) _  _  _
(_)    _  _  _  _ (_)(_)(_) _  _(_)(_)(_)(_)  (_)(_)(_)(_)_
(_)   (_)(_)(_)(_)         (_)(_)_  _  _  _   (_)        (_)
(_)         (_)(_)         (_)  (_)(_)(_)(_)_ (_)        (_)
(_) _  _  _ (_)(_) _  _  _ (_)   _  _  _  _(_)(_)        (_)
   (_)(_)(_)(_)   (_)(_)(_)     (_)(_)(_)(_)  (_)        (_)

\e[39m'
elif [ $randNum -eq 9 ]; then
	echo -e '\e[1m\e[92m
 ___               _
/  _>   ___   ___ | |_
| <_/\ / . \ <_-< | . |
`____/ \___/ /__/ |_|_|
\e[39m'
elif [ $randNum -eq 10 ]; then
	echo -e '\e[1m\e[92m
 _______    _______    _______
(  ____ \  (  ___  )  (  ____ \  |\     /|
| (    \/  | (   ) |  | (    \/  | )   ( |
| |        | |   | |  | (_____   | (___) |
| | ____   | |   | |  (_____  )  |  ___  |
| | \_  )  | |   | |        ) |  | (   ) |
| (___) |  | (___) |  /\____) |  | )   ( |
(_______)  (_______)  \_______)  |/     \|
\e[39m'
elif [ $randNum -eq 11 ]; then
	echo -e '\e[1m\e[92m
       dBBBBb  dBBBBP.dBBBBP   dBP dBP
              dBP.BP BP
   d BBBB   dBP.BP  BBBBb  dBBBBBP
   dB  BB  dBP.BP      dBP dBP dBP
  dBBBBBB dBBBBP  dBBBBP dBP dBP
\e[39m'
elif [ $randNum -eq 12 ]; then
	echo -e '\e[1m\e[92m
eeeee eeeee eeeee e   e
8   8 8  88 8   " 8   8
8e    8   8 8eeee 8eee8
88 "8 8   8    88 88  8
88ee8 8eee8 8ee88 88  8
\e[39m'
elif [ $randNum -eq 13 ]; then
	echo -e '\e[1m\e[92m
              #
              #
 ###  ##  ### ###
#  # #  # ##  # #
#  # #  #   # # #
####  ##  ### # #
   #
####
\e[39m'
elif [ $randNum -eq 14 ]; then
	echo -e '\e[1m\e[92m
                          [..
   [..      [..     [.... [..
 [..  [.. [..  [.. [..    [. [.
[..   [..[..    [..  [... [..  [..
 [..  [.. [..  [..     [..[.   [..
     [..    [..    [.. [..[..  [..
  [..
\e[39m'
elif [ $randNum -eq 15 ]; then
	echo -e '\e[1m\e[92m
  ______  _____  _______ _     _
 |  ____ |     | |______ |_____|
 |_____| |_____| ______| |     |
\e[39m'
elif [ $randNum -eq 16 ]; then
	echo -e '\e[1m\e[92m
                              oooo        
                              8888        
 .oooooooo  .ooooo.   .oooo.o  888 .oo.   
8888 888b  d888 888b d88(  88  888P8Y88b  
888   888  888   888 88Y88b.   888   888  
888bod8P8  888   888 o.  )88b  888   888  
88oooooo.  8Y8bod8P8 888888P8 o888o o888o 
d8     YD                                 
8Y88888P8
\e[39m'
elif [ $randNum -eq 17 ]; then
	echo -e '\e[1m\e[92m
                                          / 
                                        /   
           ____     ____     ____     / __  
         /     )  /     )--/     )--/     ) 
       /     /  /     /    ---,   /     /   
      (___,/(__(___,/   (___,/  /     /(__  
         /                                  
 /     /                                    
(___,/ 
\e[39m'
elif [ $randNum -eq 18 ]; then
	echo -e '\e[1m\e[92m
  ___   __   ____  _  _ 
 / __) /  \ / ___)/ )( \
( (_ \(  O )\___ \) __ (
 \___/ \__/ (____/\_)(_/
\e[39m'
else
	echo -e "\e[1m\e[92m
      ::::::::        ::::::::        ::::::::        :::    :::
    :+:    :+:      :+:    :+:      :+:    :+:       :+:    :+:
   +:+             +:+    +:+      +:+              +:+    +:+
  :#:             +#+    +:+      +#++:++#++       +#++:++#++
 +#+   +#+#      +#+    +#+             +#+       +#+    +#+
#+#    #+#      #+#    #+#      #+#    #+#       #+#    #+#
########        ########        ########        ###    ###
    \e[39m"
fi
git clone https://github.com/gosh-terminal/gosh.git
cd gosh/src || exit
go get -v -t -d ./...
go build -o gosh -- *.go
touch history.txt
mv history.txt "$GOPATH"/bin
mv gosh "$GOPATH"/bin
cd ../..
rm -rf gosh
