#!/bin/bash
nim c --verbosity:0 --hints:off src/commands/help.nim && mv src/commands/help src/commands/bin
nim c --verbosity:0 --hints:off src/commands/prompt.nim && mv src/commands/prompt src/commands/bin
go run src/gosh.go
