name: CI
on: push
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
      with:
        version: 12
    - run: |
        export PATH=$PATH:$GOPATH/bin
        python3 install.py
        go install
        gosh
