name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: test setup script
      run: |
        curl https://raw.githubusercontent.com/JesterOrNot/gosh/gopath/setup.sh | bash
